class GNSSObservations:
    def __init__(self):
        self.pr1_M = ''
        self.ph1_M = ''
        self.pr2_M = ''
        self.ph2_M = ''
        self.N1_M = ''
        self.N2_M = ''
        self.e1_Mx = ''
        self.e1_My = ''
        self.e1_Mz = ''
        self.dop1_M = ''
        self.dop2_M,
        self.pr1_R = ''
        self.ph1_R = ''
        self.pr2_R = ''
        self.ph2_R = ''
        self.N1_R = ''
        self.N2_R = ''
        self.e1_Rx = ''
        self.e1_Ry = ''
        self.e1_Rz = ''
        self.dop1_R = ''
        self.dop2_R = ''
        self.Xb0 = ''
