class GNSSObservations:
    def __init__(self, init):
        self.pr1_M = init
        self.ph1_M = init
        self.pr2_M = init
        self.ph2_M = init
        self.N1_M = init
        self.N2_M = init
        self.e1_Mx = init
        self.e1_My = init
        self.e1_Mz = init
        self.dop1_M = init
        self.dop2_M = init
        self.pr1_R = init
        self.ph1_R = init
        self.pr2_R = init
        self.ph2_R = init
        self.N1_R = init
        self.N2_R = init
        self.e1_Rx = init
        self.e1_Ry = init
        self.e1_Rz = init
        self.dop1_R = init
        self.dop2_R = init
        self.Xb0 = init
